name: example
description: Ioasys Example

publish_to: "none"

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  br_build: $runner build
  br_watch: $clean & $get & $runner watch
  br_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^3.1.1
  flutter_triple: ^1.0.5+1
  dio: ^5.0.3
  dartz: ^0.10.0-nullsafety.1
  asuka: ^2.0.0-nullsafety.2
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  effective_dart: ^1.3.1
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  http_mock_adapter: ^0.4.2
  mockito: ^5.3.2
  triple_test: ^0.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
